<template>
  <div class="reporting-view">
    <header class="flex justify-between items-center mb-10">
      <div>
        <h1>Reporting & Analytics</h1>
        <p class="text-muted">Comprehensive performance metrics and compliance reporting for your board.</p>
      </div>
      <div class="flex gap-3">
        <button class="btn btn-outline" @click="notify('Preparing Export', 'Compiling board activity report...', 'info')">
          <DownloadIcon :size="18" class="mr-2" /> Export PDF
        </button>
        <button class="btn btn-primary" @click="notify('Generating', 'Creating executive summary via AI...', 'success')">
          <SparklesIcon :size="18" class="mr-2" /> AI Summary
        </button>
      </div>
    </header>

    <!-- Analytics Charts Placeholder (High-End Visuals) -->
    <div class="grid grid-cols-12 gap-8 mb-12">
      <div class="col-span-12 lg:col-span-8 card p-8 border-t-4 border-indigo-500">
        <div class="flex justify-between items-center mb-8">
          <h3 class="font-bold">Strategy Performance (ZCCM-IH)</h3>
          <div class="flex gap-2">
            <span class="badge badge-indigo">Q1-Q2 2026</span>
          </div>
        </div>
        
        <div class="chart-container h-64 bg-slate-50 rounded-2xl flex items-end justify-around p-8 border border-dashed border-slate-200">
          <div v-for="bar in barData" :key="bar.label" class="flex flex-col items-center gap-4 w-12">
            <div class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{{ bar.value }}%</div>
            <div class="w-full bg-gradient-to-t from-indigo-600 to-indigo-400 rounded-lg transition-all duration-1000 shadow-lg shadow-indigo-100" :style="{ height: bar.height + 'px' }"></div>
            <div class="text-[10px] font-bold text-slate-600 truncate w-full text-center">{{ bar.label }}</div>
          </div>
        </div>
      </div>

      <div class="col-span-12 lg:col-span-4 card p-8 bg-slate-900 text-white">
        <h3 class="font-bold mb-6">Decision Distribution</h3>
        <div class="space-y-6">
          <div v-for="item in distribution" :key="item.label" class="space-y-2">
            <div class="flex justify-between text-xs font-bold uppercase tracking-wider text-slate-400">
              <span>{{ item.label }}</span>
              <span>{{ item.count }}</span>
            </div>
            <div class="w-full h-1.5 bg-slate-800 rounded-full">
              <div class="h-full rounded-full" :class="`bg-${item.color}-500`" :style="{ width: item.percent + '%' }"></div>
            </div>
          </div>
        </div>
        <div class="mt-12 pt-8 border-t border-slate-800 text-center">
          <div class="text-3xl font-black text-primary">42</div>
          <div class="text-[10px] text-slate-500 uppercase font-black tracking-widest mt-2">Total Decisions in 2026</div>
        </div>
      </div>
    </div>

    <!-- Reports Table -->
    <div class="card p-0">
      <div class="p-8 border-b">
        <h3 class="font-bold">Generated Board Reports</h3>
      </div>
      <div v-for="rep in reports" :key="rep.name" class="flex items-center gap-6 p-6 border-b last:border-0 hover:bg-slate-50 transition-all cursor-pointer">
        <div class="w-12 h-12 rounded-xl bg-slate-100 flex items-center justify-center text-slate-600">
          <FileTextIcon :size="24" />
        </div>
        <div class="flex-1">
          <div class="font-bold text-slate-900 mb-1">{{ rep.name }}</div>
          <div class="text-xs text-muted">Generated by {{ rep.author }} on {{ rep.date }}</div>
        </div>
        <div class="flex items-center gap-4">
          <span class="badge" :class="`badge-${rep.color}`">{{ rep.type }}</span>
          <button class="p-2 text-slate-400 hover:text-primary transition-colors">
            <DownloadIcon :size="20" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, inject } from 'vue'
import { Download as DownloadIcon, Sparkles as SparklesIcon, FileText as FileTextIcon } from 'lucide-vue-next'

const notify = inject('notify')

const barData = [
  { label: 'Mining', value: 85, height: 160 },
  { label: 'Agriculture', value: 42, height: 80 },
  { label: 'Energy', value: 68, height: 130 },
  { label: 'Tech', value: 92, height: 180 },
  { label: 'Finance', value: 55, height: 110 }
]

const distribution = [
  { label: 'Strategic', percent: 45, count: 18, color: 'indigo' },
  { label: 'Compliance', percent: 30, count: 12, color: 'emerald' },
  { label: 'Expansion', percent: 15, count: 8, color: 'cyan' },
  { label: 'Personnel', percent: 10, count: 4, color: 'rose' }
]

const reports = [
  { name: 'Board Performance Annual Summary 2025', author: 'Mwila Phiri', type: 'Annual', color: 'indigo', date: 'Jan 15, 2026' },
  { name: 'Q1 ESG Compliance Audit Trail', author: 'Mutale Chanda', type: 'Audit', color: 'rose', date: 'Mar 10, 2026' },
  { name: 'Risk Mitigation Strategy Highlights', author: 'AI Engine', type: 'Strategy', color: 'cyan', date: 'Yesterday' }
]
</script>
